version: '3.8'

services:
  devai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devai-assistant
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./docs:/app/docs
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    command: python src/core/setup_manager.py
    restart: unless-stopped
